esphome:
  name: air-sensor
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:
  password: !secret air-sensor-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.130
    gateway: 192.168.0.254
    subnet: 255.255.255.0  

i2c:
  sda: D2
  scl: D1
  scan: true

sensor:
  - platform: ccs811
    address: 0x5A
    eco2:
      name: "eCO2 Value"
    tvoc:
      name: "VOC Value"
    update_interval: 30s
    temperature: inside_temperature
    humidity: inside_humidity
    baseline: 0x4EB7
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.clothing_temp_temperature
    internal: true
  - platform: homeassistant
    id: inside_humidity
    entity_id: sensor.clothing_temp_humidity
    internal: true